services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lungscan-backend
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./app.py:/app/app.py
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    driver: bridge 